DROP TABLE IF EXISTS Polls;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Options;

CREATE TABLE Polls (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL
);

CREATE TABLE Questions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	pollId INTEGER  NOT NULL,
	type TEXT NOT NULL,
	text TEXT NOT NULL,
	FOREIGN KEY (pollId) REFERENCES Polls(id)
);

CREATE TABLE Options (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	questionId INTEGER,
	text TEXT,
	FOREIGN KEY (questionsId) REFERENCES Question(id)
);
